// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmC6Ju-TMrifv8VUJGhRjzuxMfpuoE8Sc',
    appId: '1:692227431556:web:779ddbd8b6a9c9fe1f36d1',
    messagingSenderId: '692227431556',
    projectId: 'lolo-3da0a',
    authDomain: 'lolo-3da0a.firebaseapp.com',
    storageBucket: 'lolo-3da0a.appspot.com',
    measurementId: 'G-9Q3EE42EBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvj1KLS-UCESDZJ3sRoMpE3CnHnUR3R1o',
    appId: '1:692227431556:android:572e4bcd058be80c1f36d1',
    messagingSenderId: '692227431556',
    projectId: 'lolo-3da0a',
    storageBucket: 'lolo-3da0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD9usuNU8rUjrDeu-zNMbEbFKA31NCVOU',
    appId: '1:692227431556:ios:9d6ae96f492ba0821f36d1',
    messagingSenderId: '692227431556',
    projectId: 'lolo-3da0a',
    storageBucket: 'lolo-3da0a.appspot.com',
    iosBundleId: 'com.lolo.taxi.rider',
  );
}
